% driver for tbiNMBL.subject_tbiNMBL

%% create abstract plots

% abstract = tbiNMBL.tbiNMBL()
% abstract.setHealthySubject(hy_all)
% abstract.list()
%  abstract.addSubject(tbi07)
% abstract.correlateSubjects(1,2,1,2);

abstract.compareHealthyPlots(1)
DGI = [13 23; 10 18]
abstract.plotDGIvsCorr(DGI)

%%
close all
hy_all.plotSubject([1 2 3 4  ],[ 1 1 1 1])
hy_all.plotSubject([1 2 3 4 ],[2 2 2 2])


%% check baseline improvement
baseline_corr = hy_all.correlationAcrossTestPoints(1); % check improvement, baseline
%% check overground improvement
overground_corr = hy_all.correlationAcrossTestPoints(2); % check improvement, overground


%% new subject

hy_all = tbiNMBL.subject_tbiNMBL();
hy_all.addTestPoint;
%%
hy_all.addTrial(1); % Add baseline to tp1
hy_all.addTrial(1); % add overground to tp1
%%
hy_all.plotTestPoint(1,1) % plot, and check emg labels


%% add second testPoint
hy_all.addTestPoint;
hy_all.addTrial(2); % Add baseline to tp2
hy_all.addTrial(2); % add overground to tp2
hy_all.addTrial(2); % add preferred to tp2
hy_all.plotTestPoint(2,1) % plot, and check emg labels


%% add testpoint 6
hy_all.addTestPoint;
hy_all.addTrial(3); % Add baseline to tp6
hy_all.addTrial(3); % add overground to tp6
hy_all.addTrial(3); % add preferred to tp6
hy_all.plotTestPoint(3,1) % plot, and check emg labels


%% add testpoint 10
hy_all.addTestPoint;
hy_all.addTrial(4); % Add baseline to tp10
hy_all.addTrial(4); % add overground to tp10
hy_all.addTrial(4); % add preferred to tp10
hy_all.plotTestPoint(4,1) % plot, and check emg labels


%% show data
hy_all.list
hy_all.plotSubject([1 2 ],[ 1 1]) % plot subject baseline over successive testpoints
hy_all.plotSubject([1 2 ],[ 2 2]) % plot subject overground over successive testpoints


%% check consistency
hy_all.correlationOfTestPoint(1); % check consistency
hy_all.correlationOfTestPoint(2); % check consistency
hy_all.correlationOfTestPoint(3); % check consistency
hy_all.correlationOfTestPoint(4); % check consistency

%% optionally, if emg labels are out of order, for some trials
% tbi07.fixSensor1Data(1) % for testPoint 1
% tbi07.fixSensor1Data(2) % for testPoint 2
% tbi07.fixSensor1Data(3) % for testPoint 6
% tbi07.fixSensor1Data(4) % for testPoint 10

%% compare to healthy subject
% tbi01.correlationBetweenSubjects(hy08); % compare to a healthy subject
return

%%  create healthy subject
hy08 = tbiNMBL.subject_tbiNMBL();
hy08.addTestPoint;
hy08.addTrial(1); % Add baseline to tp1
hy08.addTrial(1); % add overground to tp1
hy08.list
hy08.correlationOfTestPoint(1); % check consistency of subject across the tp
hy08.plotTestPoint(1,1)

%% calculate healthy subject average 
% don't include bad data

% right tib Anterior
i = 1;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i)];
hy_rTA = mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i)];
hy_rTA_std = mean(hy_all_selection');

% left tib Anterior
i = 7;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy02.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i)];
hy_lTA = mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy02.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i)];
hy_lTA_std = mean(hy_all_selection');

% right gastroc
i = 2;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy02.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_rGAS =  mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy02.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_rGAS_std =  mean(hy_all_selection');

% left gastroc
i = 8;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy02.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_lGAS =  mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy02.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_lGAS_std =  mean(hy_all_selection');

% right soleus
i = 3;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy02.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_rSOL =  mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy02.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_rSOL_std =  mean(hy_all_selection');


% left soleus
i = 9;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy02.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_lSOL =  mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy02.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_lSOL_std =  mean(hy_all_selection');

% right Vastus lateralis
i = 4;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_rVL =  mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_rVL_std =  mean(hy_all_selection');

% left vast lat
i = 10;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_lVL =  mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_lVL_std =  mean(hy_all_selection');

% right rectus femoris
i = 5;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy02.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_rRF =  mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy02.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_rRF_std =  mean(hy_all_selection');

% left rectus femoris
i = 11;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy02.testPoints{1}.trials{1}.emgData(:,i),...
hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_lRF =  mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy02.testPoints{1}.trials{1}.emgStd(:,i),...
hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_lRF_std =  mean(hy_all_selection');

% right hamstring
i = 6;
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_rSEMI =  mean(hy_all_selection');
hy_all_selection = ...
[hy01.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_rSEMI_std =  mean(hy_all_selection');

% left hamstring
i = 12;
hy_all_selection = ...
[hy03.testPoints{1}.trials{1}.emgData(:,i),...
hy04.testPoints{1}.trials{1}.emgData(:,i),...
hy05.testPoints{1}.trials{1}.emgData(:,i),...
hy06.testPoints{1}.trials{1}.emgData(:,i),...
hy07.testPoints{1}.trials{1}.emgData(:,i),...
hy08.testPoints{1}.trials{1}.emgData(:,i)];
hy_lSEMI =  mean(hy_all_selection');
hy_all_selection = ...
[hy03.testPoints{1}.trials{1}.emgStd(:,i),...
hy04.testPoints{1}.trials{1}.emgStd(:,i),...
hy05.testPoints{1}.trials{1}.emgStd(:,i),...
hy06.testPoints{1}.trials{1}.emgStd(:,i),...
hy07.testPoints{1}.trials{1}.emgStd(:,i),...
hy08.testPoints{1}.trials{1}.emgStd(:,i)];
hy_lSEMI_std =  mean(hy_all_selection');

% compile them all
hy_allMuscles = [hy_rTA' hy_rGAS' hy_rSOL' hy_rVL' hy_rRF' hy_rSEMI' hy_lTA' hy_lGAS' hy_lSOL' hy_lVL' hy_lRF' hy_lSEMI'];
hy_allMuscles_std = [hy_rTA_std' hy_rGAS_std' hy_rSOL_std' hy_rVL_std' hy_rRF_std' hy_rSEMI_std' hy_lTA_std' hy_lGAS_std' hy_lSOL_std' hy_lVL_std' hy_lRF_std' hy_lSEMI_std'];

hy_all.testPoints{1}.trials{1}.emgData = hy_allMuscles;
hy_all.testPoints{1}.trials{1}.emgStd = hy_allMuscles_std;
disp('yy')

